Controllers/CategoryController.cs
using Books.Models;
using Books.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TLMS.WebApp.Authorization;

namespace Books.Controllers
{
    [Authorized]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoryController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Category
        public ActionResult Index()
        {
            var categories = _context.Categories.ToList();
            return View(categories);
        }

        // GET: Category/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Category/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View("CategoryForm");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(CategoryViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("CategoryForm", model);
            }
           if(model.Id == 0)
            {
                Category category = new Category()
                {
                    Name = model.Name,
                    IsActive = model.IsActive
                };
                _context.Categories.Add(category);
            }
            else
            {
                var category = _context.Categories.Find(model.Id);
                if (category == null)
                    return HttpNotFound();

                category.Name = model.Name;
                category.IsActive = model.IsActive;
                _context.SaveChanges();
                TempData["Message"] = "Done";
            }
                _context.SaveChanges();
            return View("CategoryForm");
        }


        // GET: Category/Edit/5

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var category = _context.Categories.Find(id);
            if (category == null)
                return HttpNotFound();

            CategoryViewModel cat = new CategoryViewModel()
            {
                Name = category.Name,
                IsActive = category.IsActive
            };

            return View("CategoryForm", cat);
        }

       



    }
}

Controllers/CustomerController.cs
using Books.Models;
using Books.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Books.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CustomerController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Customer
        public ActionResult Index()
        {
            var customers = _context.Customers.ToList();
            return View(customers);
        }

        public ActionResult Create()
        {
            return View("CustomerForm");
        }

        public ActionResult Edit(int id)
        {
            var customer = _context.Customers.Find(id);

            if(customer == null)
            {
                return HttpNotFound();

            }

            CustomerViewModel viewModel = new CustomerViewModel()
            {
                Id = customer.Id,
                FirstName = customer.FirstName,
                LastName = customer.LastName,
                Phone = customer.Phone,
                Email = customer.Email,
                Gender =(Books.ViewModels.GenderEnum)customer.Gender
            };

            return View("CustomerForm", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(CustomerViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("CustomerForm", model);
            }
            if (model.Id == 0)
            {
                Customer customer = new Customer()
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Address = model.Address,
                    Gender = (Books.Models.GenderEnum)model.Gender,  
                    Email = model.Email

                };
                _context.Customers.Add(customer);
            }
            else
            {
                var customer = _context.Customers.Find(model.Id);
                if (customer == null)
                    return HttpNotFound();

                customer.FirstName = model.FirstName;
                customer.LastName = model.LastName;
                _context.SaveChanges();
                TempData["Message"] = "Done";
            }
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/InvoiceController.cs
using Books.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Books.ViewModels;

namespace Books.Controllers
{
    public class InvoiceController : Controller
    {
        private readonly ApplicationDbContext _context;
        public InvoiceController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Invoice
        public ActionResult Index()
        {
            var invoices = _context.Invoices.ToList();
            return View(invoices);
        }

        public ActionResult Create()
        {
            var model = new InvoiceFormViewModel
            {
                Customers = _context.Customers.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.FirstName }),
                Products = _context.Products.ToList(),
                InvoiceDate = DateTime.Now,
               
               
            };

            return View("InvoiceForm", model);
        }

        public ActionResult Save(InvoiceFormViewModel model , string Price,string Quantity)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Create");
            }
            Invoice nn = new Invoice()
            {
                CustomerId = model.CustomerId,
                InvoiceDate = DateTime.Now,
                InvoiceDiscount = model.InvoiceDiscount,
                //InvoiceDetails = model.InvoiceDetails.Select(d => new InvoiceDetail
                //{
                //    ProductId = d.ProductId,
                //    Quantity = d.Quantity,
                //    Price = d.Price,
                //}).ToList()
            };
            _context.Invoices.Add(nn);
            _context.SaveChanges();
            InvoiceDetail id = new InvoiceDetail()
            {
                InvoiceId = nn.InvoiceId,
                Price = decimal.Parse(Price),
                Quantity = int.Parse(Quantity),
            };

            _context.Invoices.Add(nn);
            _context.SaveChanges();
      


            return RedirectToAction("Index" );
        }


    }
}

Controllers/UsersController.cs
using Books.Models;
using Books.ViewModels;
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using BCrypt.Net;
using Books.Utilities;
using Books.Authorization;
using TLMS.WebApp.Authorization;

namespace Books.Controllers
{
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UsersController()
        {
            _context = new ApplicationDbContext();
        }

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult SignUp()
        {
            return View("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp(SignUpViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Password != model.ConfirmPassword)
                {
                    ViewBag.ErrorMessage = "Passwords do not match.";
                    return View(model);
                }

                bool existingUser = _context.Users.Any(u => u.UserName == model.UserName);
                if (existingUser)
                {
                    ViewBag.ErrorMessage = "Username is already taken.";
                    return View("Index", model);
                }

                var hashedPassword = Security.Encrypt(model.Password);

                var newUser = new User
                {
                    UserName = model.UserName,
                    Password = hashedPassword
                };

                _context.Users.Add(newUser);
                _context.SaveChanges();
                ViewBag.ErrorMessage = "Done";

                return RedirectToAction("Login");
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]



        public ActionResult Language(string lang)
        {

            HttpCookie cookie = new HttpCookie("lang", lang);
            cookie.Expires = DateTime.Now.AddYears(1);
            Response.Cookies.Add(cookie);

            return Redirect(Request.UrlReferrer.ToString());
        }


        public ActionResult Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                string deviceId = Request.UserAgent;

                var pass = Security.Encrypt(model.Password);
                var user = _context.Users.FirstOrDefault(u => u.UserName == model.UserName && u.Password == pass);
                if (user == null)
                {
                    ViewBag.ErrorMessage = "اسم المستخدم أو كلمة المرور غير صحيحة.";
                    return View(model);
                }
                VTSAuth auth = new VTSAuth();

                User loggedUser = new User()
                {
                    UserName = model.UserName,
                    Password = pass,
                   
                };
                //Session session = new Session()
                //{
                //    UserId = user.Id,
                //    DeviceId = deviceId,
                //    ExpirationTime = DateTime.Now.AddHours(3)
                //};
                //_context.Sessions.Add(session);

                auth.SaveToCookies(loggedUser);
                _context.SaveChanges();


                TempData["UserName"] = user.UserName;
                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        public ActionResult Logout()
        {
            VTSAuth auth = new VTSAuth();

            auth.ClearCookies();

            return RedirectToAction("Login");
        }
    }
}

Views/Shared/_Layout.cshtml
@using Books.Models
@using Books.Resources
@{
    var user = (User)TempData["UserInfo"];
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f9f9f9;
        }

        .navbar {
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }

        .nav-link {
            color: #ffffff !important;
            transition: color 0.3s;
        }

            .nav-link:hover {
                color: #ffc107 !important;
            }

        .language-switch {
            margin-left: auto;
            color: #fff;
        }

        .container.body-content {
            padding-top: 30px;
            padding-bottom: 50px;
            min-height: 80vh;
        }

        footer {
            background-color: #343a40;
            color: white;
            padding: 20px 0;
            text-align: center;
            margin-top: 30px;
        }

            footer p {
                margin: 0;
            }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-3">
        <div class="container">
            <a class="navbar-brand fw-bold" href="/">📚 My Book App</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">@Html.ActionLink("Categories", "Index", "Category", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Products", "Index", "Products", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Customers", "Index", "Customer", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Invoices", "Index", "Invoice", null, new { @class = "nav-link" })</li>
                    @if (user != null)
                    {
                        <li class="nav-item">@Html.ActionLink("تسجيل الخروج", "Logout", "Users", null, new { @class = "nav-link" })</li>
                    }
                </ul>
                <div class="language-switch d-flex align-items-center">
                    <a class="nav-link" href="/Language/ChangeLanguage?lang=ar">عربي</a>
                    <span class="text-white px-1">|</span>
                    <a class="nav-link" href="/Language/ChangeLanguage?lang=en">English</a>
                </div>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
    </div>

    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        let inactivityTime = 1000000;
        let timeout;

        function resetTimer() {
            clearTimeout(timeout);
            timeout = setTimeout(showPrompt, inactivityTime);
        }

        function showPrompt() {
            let userResponse = confirm("هل تريد الاستمرار في تصفح الموقع؟");
            if (!userResponse) {
                window.close();
            } else {
                resetTimer();
            }
        }

        window.onload = resetTimer;
        document.addEventListener("mousemove", resetTimer);
        document.addEventListener("keydown", resetTimer);
        document.addEventListener("scroll", resetTimer);
        document.addEventListener("click", resetTimer);
    </script>
</body>
</html>