Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Books.Models
{
	public class Book
	{
        public int Id { get; set; }

        [Required]
        [MaxLength(256)]
        public string Title { get; set; }

        [Required]
        [MaxLength(128)]
        public string Author { get; set; }

        [Required]
        [MaxLength(2000)]
        public string Description { get; set; }

        public int CategoryId { get; set; }

        public Category Category { get; set; }

        public DateTime AddedOn { get; set; }

        public Book()
        {
            AddedOn = DateTime.Now;
        }
    }
}

Controllers/Api/BooksController.cs
using Books.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Books.Controllers.Api
{
    public class BooksController : ApiController
    {
        private readonly ApplicationDbContext _context;
        public BooksController()
        {
            _context = new ApplicationDbContext();
        }

        [HttpDelete]
        public IHttpActionResult DeleteBook(int id)
        {
            var book = _context.Books.Find(id);

            if (book == null)
                return NotFound();

            _context.Books.Remove(book);
            _context.SaveChanges();
            return Ok();
        }
    }
}

Controllers/BooksController.cs
using Books.Models;
using Books.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TLMS.WebApp.Authorization;

namespace Books.Controllers
{
    [Authorized]
    public class BooksController : Controller
    {   
        private readonly ApplicationDbContext _context;
        public BooksController()
        {
            _context = new ApplicationDbContext();            
        }
        // GET: Books

        public ActionResult Index()
        {
            var books = _context.Books.Include(x => x.Category).ToList();
            return View(books);
        }
        public ActionResult Create()
        {
            var viewModel = new BookFormViewModel()
            {
                Categories = _context.Categories.Where(x => x.IsActive).ToList()
            };

            return View("BookFrom",viewModel);
        }

        public ActionResult Save(BookFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Create");

            }
            if(model.Id == 0)
            {
                var book = new Book()
                {
                    Title = model.Title,
                    Author = model.Author,
                    CategoryId = model.CategoryId,
                    Description = model.Description

                };
                _context.Books.Add(book);
            }
            else
            {
                var book = _context.Books.Find(model.Id);
                if (book == null)
                    return HttpNotFound();

                book.Title = model.Title;
                book.Author = model.Author;
                book.CategoryId = model.CategoryId;
                book.Description = model.Description;
            }
            _context.SaveChanges();
            TempData["Message"] = "Done";

            return RedirectToAction("Index");

        }
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var book = _context.Books.Include(m => m.Category).SingleOrDefault(m => m.Id == id);

            if (book == null)
                return HttpNotFound();

            return View(book);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var book = _context.Books.Find(id);

            if (book == null)
                return HttpNotFound();

            var viewModel = new BookFormViewModel
            {
                Id = book.Id,
                Title = book.Title,
                Author = book.Author,
                CategoryId = book.CategoryId,
                Description = book.Description,
                Categories = _context.Categories.Where(m => m.IsActive).ToList()
            };

            return View("BookFrom", viewModel);
        }

    }
}

Views/Books/BookFrom.cshtml
@model Books.ViewModels.BookFormViewModel

@{
    ViewBag.Title = "Create";
}

<h2> @(Model.Id == 0 ? "Add New Book" : "Edit Book")</h2>




@using (Html.BeginForm("Save", "Books"))
{

    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.Title)
        @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Title, null, new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Author)
        @Html.TextBoxFor(m => m.Author, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Author, null, new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.CategoryId)
        @Html.DropDownListFor(m => m.CategoryId, new SelectList(Model.Categories, "Id", "Name"), "", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.CategoryId, null, new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Description)
        @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Description, null, new { @class = "text-danger" })
    </div>

    <button type="submit" class="btn btn-primary">Save</button>

}


@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Books/Details.cshtml
@model Books.Models.Book

@{
    ViewBag.Title = "Details";
}

<ul class="list-group list-group-flush">
    <li class="list-group-item bg-secondary text-white font-weight-bold d-flex justify-content-between align-items-center">
        <span>@Model.Title</span>
        <a href="@Url.Action("Edit", "Books", new { id = Model.Id })" class="btn btn-primary">
           تعديل
        </a>
    </li>
    <li class="list-group-item">@Model.Author</li>
    <li class="list-group-item">@Model.Category.Name</li>
    <li class="list-group-item">@Model.Description</li>
    <li class="list-group-item">@Model.AddedOn</li>
</ul>

Views/Books/Index.cshtml
@model IEnumerable<Books.Models.Book>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<hr />

<a href="@Url.Action("Create")" class="btn btn-primary">Add New</a>


@if (Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Category</th>
                <th>Description</th>
                <th>Added On</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var book in Model)
            {
                <tr>
                    <td>@Html.ActionLink(book.Title, "Details", "Books", new { id = book.Id }, null)</td>
                    <td>@book.Author</td>
                    <td>@book.Category.Name</td>
                    <td>@book.Description</td>
                    <td>@book.AddedOn</td>
                    <td>
                        <a href="@Url.Action("Edit", "Books", new { id = book.Id })" class="btn btn-primary">
                            <i class="icofont-ui-edit"></i>
                            Edit
                        </a>
                        <a href="javascript:;" class="btn btn-danger js-delete" data-id="@book.Id">
                            <i class="icofont-ui-close"></i>
                            Delete
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-warning" role="alert">
        No bookings available at the moment.

    </div>
}

@section Scripts{

    <script>
        $(document).ready(function () {

            toastr.options = {
                "preventDuplicates": true
            }

            var message = $('#Message').text();
            if (message !== '') {
                toastr.success(message);
            }

            $('.js-delete').on('click', function () {
                var btn = $(this);
                var result = confirm("Are You Sure To Delete This Row")
                if (result) {
                    $.ajax({
                        url: '/api/books/' + btn.data('id'),
                        method: 'DELETE',
                        success: function () {
                            if ($('tbody tr').length === 1)
                                $('table').fadeOut(function () {
                                    this.remove();
                                    $('.alert').removeClass('d-none');
                                });

                            else
                                btn.parents('tr').fadeOut(function () {
                                    this.remove();
                                });

                            toastr.success('Book deleted');
                        },
                        error: function () {
                            toastr.error('Something went wrong!');
                        }
                    });
                }
            });
        });
    </script>

}